### ISSUE TITLE
Select theme and content management approach for RoSyM website

### ISSUE THREAD

**Issue by swrede** [rosym-project/rosym-project.github.io#1]
It shall be a responsive Jekkyl theme.

**Comment by scymtym** [comment]
I think https://www.cs.york.ac.uk/robostar/ was mentioned as a possible inspiration.

**Comment by scymtym** [comment]
@swrede How about this: http://themes.jekyllrc.org/lanyon/? [Demo](http://lanyon.getpoole.com/)

**Comment by Pouya-moh** [comment]
What about what we had for cogimon? e.g., [http://cogimon.github.io/runtime/gettingstarted.html](http://cogimon.github.io/runtime/gettingstarted.html)

Although, on mobile is a bit iffy. `lanyon` mentioned above for instance, has better mobile support.

**Comment by scymtym** [comment]
> What about what we had for cogimon?

I like the cogimon theme. It seems to be based on a version of the [jekyll-new](https://github.com/jglovier/jekyll-new) theme.

I suggested lanyon because @swrede mentioned "responsive" as a requirement.

**Comment by Pouya-moh** [comment]
[EasyBook](http://themes.jekyllrc.org/easybook/) is responsive with proper MathJax support
[Demo](http://laobubu.net/jekyll-theme-EasyBook/archivers/hello)

**Comment by scymtym** [comment]
I [tried the EasyBook theme](https://rosym-project.github.io/). What do you think?

**Comment by swrede** [comment]
I am also in favor of EasyBook!

**Comment by scymtym** [comment]
Great.
